const NameList = [
    "abelha",
    "a'ndorinha",
    "babuíno",
    "baleia",
    "cachorro",
    "camaleão",
    "dragão-de-komodo",
    "dromedário",
    "ema",
    "elefante",
    "foca",
    "flamingo",
    "golfinho",
    "guaxinim",
    "hipopótamo",
    "hiena",
    "iguana",
    "impala",
    "jaguar",
    "jacaré",
    "kakapo (ave)",
    "kiwi (ave)",
    "leão",
    "lagarto",
    "macaco",
    "musaranho",
    "naja",
    "ovelha",
    "orangotango",
    "papagaio",
    "perdiz",
    "quati",
    "queixada",
    "raposa",
    "rato",
    "sardinha",
    "sagui",
    "tartaruga",
    "tamanduá-bandeira",
    "urso-polar",
    "urubu",
    "veado",
    "vaca"
    ];

  export default NameList;